// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Turnos.Data;

#nullable disable

namespace Turnos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629201000_AddMustChangePassword")]
    partial class AddMustChangePassword
    {
    }
}
